<?php

/**
 * @file
 * This is the main module file for Views Database Connector.
 */

/**
 * Implements hook_views_api().

Register View API information.

This is required for your module to have its include files loaded; for example, when implementing hook_views_default_views().

Return value
array An array with the following possible keys:

	*api: (required) The version of the Views API the module implements.
	*path: (optional) If includes are stored somewhere other than within the root module directory, specify its path here.
	*template path: (optional) A path where the module has stored it's views template files. When you have specified this key views automatically uses the template files for the views. You can use the same naming conventions like for normal views template files.



 */
function AtoM_Drupal_Connector_views_api() {
  return array(
    'api' => 3,
  );
}
